[package]
name = "gamelift-sys"
version = "0.1.0"
edition = "2021"
link = "gamelift"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
anyhow = "1.0.65"
